stages:
  - stage: Build
    jobs:
      - job: Build
        pool: ubuntu-latest
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              projects: 'sdlcdotnetcoreapps/sdlc-log-api01/sdlc-log-api01.csproj'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: 'sdlcdotnetcoreapps/sdlc-log-api01/sdlc-log-api01.csproj'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: 'sdlcdotnetcoreapps/sdlc-log-api01/sdlc-log-api01.csproj'
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  - stage: DeployDevStage
    displayName: Deploy Dev
    dependsOn: Build
    condition: succeeded()
    jobs:
    - deployment: DeployDev
      displayName: Deploy Dev
      environment: dev
      pool: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'WMSDLC Connection'
                  appType: 'webAppLinux'
                  WebAppName: 'sampleapp01'
                  packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
                  RuntimeStack: 'DOTNETCORE|1.0'
  - stage: DeployQAStage
    displayName: Deploy to QA
    dependsOn: DeployDevStage
    condition: succeeded()
    jobs:
    - deployment: DeployQA
      displayName: Deploy QA
      environment: qa
      pool: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'WMSDLC Connection'
                  appType: 'webAppLinux'
                  WebAppName: 'sampleapp01'
                  packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
                  RuntimeStack: 'DOTNETCORE|1.0'
  - stage: DeployQA2Stage
    displayName: Deploy QA2
    dependsOn: DeployQAStage
    condition: succeeded()
    jobs:
    - deployment: DeployQA2 
      displayName: SwapQABluewithGreen
      environment: qa2
      pool: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'WMSDLC Connection'
                  appType: 'webAppLinux'
                  WebAppName: 'sampleapp01'
                  packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
                  RuntimeStack: 'DOTNETCORE|1.0'
  - stage: DeployPreProdStage
    displayName: Deploy Dev
    dependsOn: Build
    condition: succeeded()
    jobs:
    - deployment: DeployDev
      displayName: Deploy Dev
      environment: preprod
      pool: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'WMSDLC Connection'
                  appType: 'webAppLinux'
                  WebAppName: 'sampleapp01'
                  packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
                  RuntimeStack: 'DOTNETCORE|1.0'
  - stage: DeployProdStage
    displayName: Deploy Prod
    dependsOn: Build
    condition: succeeded()
    jobs:
    - deployment: SwapPreProdwithProd
      displayName: Deploy Dev
      environment: prod
      pool: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'WMSDLC Connection'
                  appType: 'webAppLinux'
                  WebAppName: 'sampleapp01'
                  packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
                  RuntimeStack: 'DOTNETCORE|1.0'
  
           
