stages:
  - stage: Build
    jobs:
      - job: Build
        pool: 
          vmImage: 'ubuntu-latest'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'dotnet restore'
            inputs:
              command: 'restore'
              projects: 'sdlcdotnetcoreapps/sdlc-log-api01/sdlc-log-api01.csproj'
              arguments: '--configuration release'
          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              command: 'build'
              projects: 'sdlcdotnetcoreapps/sdlc-log-api01/sdlc-log-api01.csproj'
              arguments: '--configuration release'
          - task: DotNetCoreCLI@2
            displayName: 'dotnet publish'
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: 'sdlcdotnetcoreapps/sdlc-log-api01/sdlc-log-api01.csproj'
              arguments: '--configuration release --output $(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            displayName: 'publish to drop'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  - stage: DeployDevStage
    displayName: Deploy Dev
    dependsOn: Build
    condition: succeeded()
    jobs:
    - deployment: DeployDev
      displayName: Deploy Dev
      environment: dev
      pool: 
        vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'SDLC_Connection_linux'
                  appType: 'webAppLinux'
                  WebAppName: 'sdlcrules01-dev'
                  packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
                  RuntimeStack: 'DOTNETCORE|3.1'
  - stage: DeployQAStage
    displayName: Deploy to QA
    dependsOn: DeployDevStage
    condition: succeeded()
    jobs:
    - deployment: DeployQA
      displayName: Deploy QA
      environment: qa
      pool: 
        vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'SDLC_Connection_linux'
                  appType: 'webAppLinux'
                  WebAppName: 'sdlcrules01-qa'
                  deployToSlotOrASE: true
                  ResourceGroupName: 'WMSDLC-linux'
                  SlotName: 'blue'
                  packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
                  RuntimeStack: 'DOTNETCORE|3.1'
  - stage: DeployQA2Stage
    displayName: Deploy QA2
    dependsOn: DeployQAStage
    condition: succeeded()
    jobs:
    - deployment: DeployQA2 
      displayName: SwapQABluewithGreen
      environment: qa2
      pool: 
        vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureAppServiceManage@0
                inputs:
                  azureSubscription: 'SDLC_Connection_linux'
                  Action: 'Swap Slots'
                  WebAppName: 'sdlcrules01-qa'
                  ResourceGroupName: 'WMSDLC-linux'
                  SourceSlot: 'blue'
  - stage: DeployPreProdStage
    displayName: Deploy PreProd
    dependsOn: DeployQA2Stage
    condition: succeeded()
    jobs:
    - deployment: DeployPreProd
      displayName: Deploy PreProd
      environment: preprod
      pool: 
        vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'SDLC_Connection_linux'
                  appType: 'webAppLinux'
                  WebAppName: 'sdlcrules01'
                  deployToSlotOrASE: true
                  ResourceGroupName: 'WMSDLC-linux'
                  SlotName: 'blue'
                  packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
                  RuntimeStack: 'DOTNETCORE|3.1'
  - stage: DeployProdStage
    displayName: Deploy Prod
    dependsOn: DeployPreProdStage
    condition: succeeded()
    jobs:
    - deployment: SwapProdBluewithGreen
      displayName: Deploy to Prod
      environment: prod
      pool: 
        vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureAppServiceManage@0
                inputs:
                  azureSubscription: 'SDLC_Connection_linux'
                  Action: 'Swap Slots'
                  WebAppName: 'sdlcrules01'
                  ResourceGroupName: 'WMSDLC-linux'
                  SourceSlot: 'blue'
  
           
